project:
  type: website

website:
  title: Prediction of Tornado Occurance in Tornado Valley
  navbar:
    right:
      - icon: github
        href: https://github.com/TylerHart740/info-523-su25-Hart_Final # Need to change to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
